"use client";

/**
 * The prioritized action list: the primary product surface.
 *
 * Replaces the 9 manual workflow buttons. Actions are ranked by estimated
 * traffic impact, and each row can be expanded to show the CTR arithmetic that
 * produced its projection, so a ranking is never just a number.
 */

import { useCallback, useEffect, useState } from "react";
import {
  ActionItem,
  ActionList as ActionListResponse,
  fetchActions,
  fmtNum,
} from "@/lib/intelligence";

interface Props {
  websiteId: string;
  onCountChange?: (count: number) => void;
}

const CATEGORY_COLOR: Record<string, string> = {
  technical: "var(--accent)",
  content: "#8b5cf6",
  links: "#06b6d4",
  cro: "var(--amber)",
  intelligence: "var(--green)",
};

function severityBadge(severity?: string) {
  switch (severity) {
    case "critical":
      return "badge-red";
    case "high":
      return "badge-amber";
    default:
      return "badge-muted";
  }
}

export function ActionList({ websiteId, onCountChange }: Props) {
  const [data, setData] = useState<ActionListResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<"traffic_impact" | "effort">(
    "traffic_impact"
  );
  const [limit, setLimit] = useState(10);
  const [expanded, setExpanded] = useState<string | null>(null);

  const load = useCallback(async () => {
    if (!websiteId) {
      setLoading(false);
      return;
    }
    try {
      setLoading(true);
      setError(null);
      const res = await fetchActions(websiteId, limit, sortBy);
      setData(res);
      onCountChange?.(res.count);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load actions");
      setData(null);
    } finally {
      setLoading(false);
    }
  }, [websiteId, limit, sortBy, onCountChange]);

  useEffect(() => {
    load();
  }, [load]);

  const actions = data?.actions ?? [];

  return (
    <div className="panel" style={{ marginBottom: "16px" }}>
      <div className="panel-head">
        <span
          className="panel-label"
          style={{ display: "flex", alignItems: "center", gap: "8px" }}
        >
          <span>◆ Prioritized Action List</span>
          {data && (
            <span className="badge badge-accent">
              {data.count} ranked of {data.total_open} open
            </span>
          )}
        </span>
        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
          <span
            style={{
              fontSize: "10px",
              color: "var(--muted)",
              textTransform: "uppercase",
              letterSpacing: "0.05em",
            }}
          >
            Sort
          </span>
          <select
            className="site-select"
            value={sortBy}
            onChange={(e) =>
              setSortBy(e.target.value as "traffic_impact" | "effort")
            }
            style={{ fontSize: "10px", padding: "4px 8px" }}
          >
            <option value="traffic_impact">Estimated traffic impact</option>
            <option value="effort">Impact per hour</option>
          </select>
          <select
            className="site-select"
            value={limit}
            onChange={(e) => setLimit(Number(e.target.value))}
            style={{ fontSize: "10px", padding: "4px 8px" }}
          >
            <option value={10}>Top 10</option>
            <option value={25}>Top 25</option>
            <option value={50}>Top 50</option>
          </select>
          <button className="panel-action" onClick={load} disabled={loading}>
            {loading ? "Loading" : "Refresh"}
          </button>
        </div>
      </div>

      <div className="panel-body" style={{ padding: 0 }}>
        {!websiteId && (
          <div
            style={{
              padding: "28px 16px",
              textAlign: "center",
              fontSize: "11.5px",
              color: "var(--muted)",
            }}
          >
            Select a website to load its prioritized actions.
          </div>
        )}

        {websiteId && error && (
          <div
            style={{
              padding: "16px",
              fontSize: "11.5px",
              color: "var(--red)",
            }}
          >
            {error}
          </div>
        )}

        {websiteId && !error && !loading && actions.length === 0 && (
          <div
            style={{
              padding: "28px 16px",
              textAlign: "center",
              fontSize: "11.5px",
              color: "var(--muted)",
              lineHeight: 1.6,
            }}
          >
            No ranked actions yet.
            <br />
            Actions are generated by the analyses (indexation, on-page, decay,
            CRO) and ranked once search volume and positions are known.
          </div>
        )}

        {actions.length > 0 && (
          <table className="data-table">
            <thead>
              <tr>
                <th style={{ width: "38px" }}>#</th>
                <th>Action</th>
                <th style={{ width: "110px" }}>Projected clicks</th>
                <th style={{ width: "80px" }}>Effort</th>
                <th style={{ width: "90px" }}>Confidence</th>
                <th style={{ width: "80px" }} />
              </tr>
            </thead>
            <tbody>
              {actions.map((a: ActionItem) => {
                const key = a.id || `${a.rank}-${a.title}`;
                const isOpen = expanded === key;
                const color = CATEGORY_COLOR[a.category] || "var(--muted)";
                return (
                  <>
                    <tr
                      key={key}
                      onClick={() => setExpanded(isOpen ? null : key)}
                      style={{ cursor: "pointer" }}
                    >
                      <td>
                        <span
                          style={{
                            fontWeight: 700,
                            fontSize: "12px",
                            color: (a.rank ?? 0) <= 3 ? "var(--accent)" : "var(--ink)",
                          }}
                        >
                          {a.rank}
                        </span>
                      </td>
                      <td>
                        <div
                          style={{
                            display: "flex",
                            alignItems: "center",
                            gap: "6px",
                            marginBottom: "2px",
                          }}
                        >
                          <span
                            style={{
                              fontSize: "8.5px",
                              textTransform: "uppercase",
                              padding: "1px 5px",
                              border: `1px solid ${color}`,
                              color,
                              borderRadius: "2px",
                              fontWeight: 700,
                            }}
                          >
                            {a.category}
                          </span>
                          {a.severity && (
                            <span
                              className={`badge ${severityBadge(a.severity)}`}
                              style={{ fontSize: "8.5px" }}
                            >
                              {a.severity}
                            </span>
                          )}
                        </div>
                        <div
                          style={{
                            fontSize: "11.5px",
                            fontWeight: 600,
                            color: "var(--ink)",
                          }}
                        >
                          {a.title}
                        </div>
                        {(a.keyword || a.target_url) && (
                          <div
                            style={{
                              fontSize: "10px",
                              color: "var(--muted)",
                              fontFamily: "monospace",
                            }}
                          >
                            {a.keyword}
                            {a.keyword && a.target_url ? " · " : ""}
                            {a.target_url}
                          </div>
                        )}
                      </td>
                      <td>
                        <span
                          style={{
                            fontWeight: 700,
                            color: "var(--green)",
                            fontSize: "12px",
                          }}
                        >
                          +{fmtNum(a.projected_clicks_gain, "0")}
                        </span>
                        <div
                          style={{
                            fontSize: "9px",
                            color: "var(--muted)",
                          }}
                        >
                          clicks/mo
                        </div>
                      </td>
                      <td style={{ fontSize: "10.5px" }}>
                        {a.effort_minutes ?? 0} min
                      </td>
                      <td style={{ fontSize: "10.5px" }}>
                        {((a.confidence ?? 0) * 100).toFixed(0)}%
                      </td>
                      <td>
                        <button
                          className="panel-action"
                          onClick={(e) => {
                            e.stopPropagation();
                            setExpanded(isOpen ? null : key);
                          }}
                        >
                          {isOpen ? "Hide" : "Why"}
                        </button>
                      </td>
                    </tr>
                    {isOpen && (
                      <tr key={`${key}-evidence`}>
                        <td
                          colSpan={6}
                          style={{
                            background: "var(--surface)",
                            padding: "12px 16px",
                          }}
                        >
                          <div
                            style={{
                              fontSize: "9px",
                              textTransform: "uppercase",
                              color: "var(--muted)",
                              letterSpacing: "0.06em",
                              marginBottom: "6px",
                            }}
                          >
                            How this rank was calculated
                          </div>
                          <div
                            style={{
                              fontFamily: "monospace",
                              fontSize: "11px",
                              color: "var(--ink)",
                              marginBottom: "10px",
                              lineHeight: 1.6,
                            }}
                          >
                            {a.evidence?.formula ||
                              a.evidence?.reason ||
                              "No scoring evidence recorded."}
                          </div>
                          <div
                            style={{
                              display: "grid",
                              gridTemplateColumns:
                                "repeat(auto-fit, minmax(120px, 1fr))",
                              gap: "8px",
                              fontSize: "10.5px",
                            }}
                          >
                            <div>
                              <span style={{ color: "var(--muted)" }}>
                                Search volume:{" "}
                              </span>
                              {fmtNum(a.search_volume)}
                            </div>
                            <div>
                              <span style={{ color: "var(--muted)" }}>
                                Position:{" "}
                              </span>
                              {a.current_position ?? "—"} →{" "}
                              {a.target_position ?? "—"}
                            </div>
                            <div>
                              <span style={{ color: "var(--muted)" }}>
                                CTR gain:{" "}
                              </span>
                              {a.evidence?.ctr_gain !== undefined
                                ? `${(a.evidence.ctr_gain * 100).toFixed(2)}%`
                                : "—"}
                            </div>
                            <div>
                              <span style={{ color: "var(--muted)" }}>
                                Impact/hr:{" "}
                              </span>
                              {a.impact_per_hour ?? "—"}
                            </div>
                            <div>
                              <span style={{ color: "var(--muted)" }}>
                                Priority score:{" "}
                              </span>
                              {a.priority_score ?? "—"}
                            </div>
                          </div>
                        </td>
                      </tr>
                    )}
                  </>
                );
              })}
            </tbody>
          </table>
        )}

        {data?.unscored_note && (
          <div
            style={{
              padding: "10px 16px",
              fontSize: "10.5px",
              color: "var(--muted)",
              borderTop: "1px solid var(--line)",
              background: "var(--surface)",
            }}
          >
            {data.unscored_note}
          </div>
        )}
      </div>
    </div>
  );
}